"""Create evidence analysis table

Revision ID: 422d6b455f03
Revises: 47b88d2de90c
Create Date: 2026-08-13 11:36:59.149494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '422d6b455f03'
down_revision: Union[str, Sequence[str], None] = '47b88d2de90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['survey_evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_analysis_analysis_type'), 'evidence_analysis', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_evidence_analysis_evidence_id'), 'evidence_analysis', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_analysis_status'), 'evidence_analysis', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_analysis_status'), table_name='evidence_analysis')
    op.drop_index(op.f('ix_evidence_analysis_evidence_id'), table_name='evidence_analysis')
    op.drop_index(op.f('ix_evidence_analysis_analysis_type'), table_name='evidence_analysis')
    op.drop_table('evidence_analysis')
    # ### end Alembic commands ###
