"""create survey evidence table

Revision ID: 47b88d2de90c
Revises: 5e01ce3a7ae0
Create Date: 2026-08-12 20:42:24.299024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47b88d2de90c'
down_revision: Union[str, Sequence[str], None] = '5e01ce3a7ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=30), server_default='photo', nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('metadata_source', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=30), server_default='uploaded', nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_survey_evidence_evidence_type'), 'survey_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_survey_evidence_file_hash'), 'survey_evidence', ['file_hash'], unique=False)
    op.create_index(op.f('ix_survey_evidence_processing_status'), 'survey_evidence', ['processing_status'], unique=False)
    op.create_index(op.f('ix_survey_evidence_survey_id'), 'survey_evidence', ['survey_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_evidence_survey_id'), table_name='survey_evidence')
    op.drop_index(op.f('ix_survey_evidence_processing_status'), table_name='survey_evidence')
    op.drop_index(op.f('ix_survey_evidence_file_hash'), table_name='survey_evidence')
    op.drop_index(op.f('ix_survey_evidence_evidence_type'), table_name='survey_evidence')
    op.drop_table('survey_evidence')
    # ### end Alembic commands ###
