"""create claims table

Revision ID: 68e5641f99e4
Revises: 03e6a9f41926
Create Date: 2026-08-11 19:57:50.720626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e5641f99e4'
down_revision: Union[str, Sequence[str], None] = '03e6a9f41926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('chassis_number', sa.String(length=100), nullable=True),
    sa.Column('engine_number', sa.String(length=100), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_address', sa.Text(), nullable=True),
    sa.Column('financer_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driving_license_number', sa.String(length=100), nullable=True),
    sa.Column('license_issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('license_issue_date', sa.Date(), nullable=True),
    sa.Column('license_valid_until', sa.Date(), nullable=True),
    sa.Column('permitted_vehicle_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cause_of_accident', sa.Text(), nullable=True),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('survey_location', sa.Text(), nullable=True),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'claim_number', name='uq_claims_user_claim_number')
    )
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index(op.f('ix_claims_user_id'), 'claims', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_user_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
